name: PR Check and build

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Commitlint
        uses: wagoid/commitlint-github-action@v5

      - name: Run tests
        run: |
          docker compose -f compose-test.yml up

      - name: Calculate SemVer Tag
        id: semver
        uses: smlx/ccv@v0.7.3  # Or another semver action of your choice
        with:
          write-tag: false   # Set to true if you want the action to push the new tag

      - name: Debug SemVer Output
        run: echo SemVerTag: ${{ steps.semver.outputs.version-string }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build
        env:
          SEMVER_TAG: ${{ steps.semver.outputs.version-string }}
        run: docker compose build

      - name: Docker Push
        run: docker compose push

      - name: Close PR if Tests Fail
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr close "$PR_NUMBER" --repo "$REPO"

      - name: Send Email Notification if Tests Fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: coleman.konopelski47@ethereal.email
          password: 5vbyDtXzydG7SdQ8Ny
          subject: "PR #${{ github.event.pull_request.number }} Closed"
          to: "coleman.konopelski47@ethereal.email"
          from: "coleman.konopelski47@ethereal.email"
          body: |
            PR #${{ github.event.pull_request.number }} Closed
            Repository: ${{ github.repository }}
            PR Link: ${{ github.event.pull_request.html_url }}
