name: PR Check and build

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Commitlint (Latest Commit)
        uses: wagoid/commitlint-github-action@v5
        with:
          firstParent: true

      - name: Run tests
        run: |
          docker compose -f compose-test.yml up

      - name: Send Email Notification if Tests Fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: coleman.konopelski47@ethereal.email
          password: 5vbyDtXzydG7SdQ8Ny
          subject: "PR #${{ github.event.pull_request.number }} Closed"
          to: "coleman.konopelski47@ethereal.email"
          from: "coleman.konopelski47@ethereal.email"
          body: |
            PR #${{ github.event.pull_request.number }} Closed
            Repository: ${{ github.repository }}
            PR Link: ${{ github.event.pull_request.html_url }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build images with docker-compose
        run: docker compose build

      - name: Push images with docker-compose
        run: docker compose push

      - name: Close PR if Tests Fail
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          gh pr close "$PR_NUMBER" --repo "$REPO"

