name: Nightly build

on:
  schedule:
    - cron: '30 21 * * *'  
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Test
        run: |
          docker compose -f compose-test.yml up
        continue-on-error: false 

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        continue-on-error: false 

      - name: Docker Build
        run: docker compose build
        env:
          SEMVER_TAG: "latest"
        continue-on-error: false 

      - name: Docker Push
        run: docker compose push
        env:
          SEMVER_TAG: "latest"
        continue-on-error: false 

      - name: Send Email Notification if Tests Fail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: coleman.konopelski47@ethereal.email
          password: 5vbyDtXzydG7SdQ8Ny
          subject: "Nightly build failed"
          to: "coleman.konopelski47@ethereal.email"
          from: "coleman.konopelski47@ethereal.email"
          body: |
            Nightly build failed
            Repository: ${{ github.repository }}

